C_LİST=[
	"Qalereyanın 7-ci şəklini aşağıdan göndər",
  "Növbəti 3 növbə üçün ləhcə ilə danışın. Fərqli dialektlərə keçsəniz, /zar əmrindən istifadə edərək 6-ya ən yaxın gələn oyunçu sizi cəzalandıracaq",
  "Üç xörək qaşığı acı sous (və ya buna bənzər bir şey) yeyin və videoya çəkin və ya qrupa atın",
  "Oyunda kimsədən 5 dəqiqəlik ev heyvanı olmasını istəyə bilərsiniz.", "Döşəməni yalayın və foto/videonu qrupa yerləşdirin",
  "/zar əmrindən istifadə edərək, 6-ya ən yaxın olan oyunçunun sosial media hesablarından birinə 5 dəqiqə vaxt verin",
  "Bir məşhuru 3 dəqiqə təqlid edin.", "Kimsə təqlid edilən sənətçini təxmin edənə qədər bir sənətçini təqlid edin",
  "Qrupun təklif etdiyi mövzu ətrafında səkkiz sətir və iki sətirdən ibarət bir şeir yazın",
  "Oyundakı insanların birgə qərarı ilə qrupdan birini öpün (ümumi qərar yoxdursa, /zar əmrindən 1-ə ən yaxın olan oyunçu ilə öpün)."
  "5 dəqiqə oyunda bir adama qul ol.", "Süpürgə və ya mopla rəqs et və video çək",
  “Əsl sevginin kim olduğunu bəyan et”, “Ağzını tərpətmədən əlifbanı başdan-ayağa oxu, oxuyarkən video çək”, “Ağıl gələn ilk sözü de.”,
  "Oyundakı oyunçulardan biri haqqında hekayə uydur", "15 saniyə ərzində əlifbanı yuxarıdan aşağı oxu, oxuyarkən səs çıxar", "İt kimi hürəndə səs çıxar",
  "Bir mahnını əvvəldən sona qədər oxuyun, ucadan çıxın,"Görüşdüyünüz ən pis və ən yaxşı insanı təsvir edin."
  "Bir dəqiqəlik əks cinsin nümayəndəsi kimi gəzin.", "Sevgilinizə edə biləcəyiniz ən alçaq mətni göndərin.",
  "Məşhur restoranlardan birinə zəng edin və onların menyusunu öyrənərkən lağ edin."
  "Keçmişinizə mesaj yazın və onu unuda bilməyəcəyinizi söyləyin.","2 dövrə "sən" sözünü eşidəndə quş kimi səslən.",
  "Telefonda brauzer tarixçəsini hamıya göstərin.
]

D_LİST = [
	"Telefonunuza ən son nə zəng etdiniz?", "Biri sizə sevgilinizdən/sevgilinizdən ayrılmaq üçün 1 milyon dollar təklif etsə, bunu edərdinizmi?",
 "Bu qrupda kimi ən az bəyənirsiniz və niyə?", "Heç sinifdə yüksək səslə geğirmisiniz?",
 "Heç sinifdə ucadan geğirmisən?", "Heç yerdən bir şey götürüb yemisən?",
 "Əgər bir gün əks cins kimi oyansanız, ilk edəcəyiniz şey nədir?",
 "Heç hovuza sidik etmisinizmi?", "Liftdə nə vaxtsa qazı buraxmısınız?",
 "Tualetdə oturarkən ağlınıza nə gəlir?", "Böyüyən xəyali dostunuz olubmu?",
 "Ən pis vərdişin nədir?", "Burnunu seçirsən?", "Hamamda mahnı oxuya bilirsənmi?",
 "Heç buna işeymisən?", "İctimaiyyət qarşısında ən utanc duyduğun an hansı olub?", "Heç güzgüdə özünlə danışmısan?",
 "Kimsə internet tarixçənizi görsə, nədən utanarsınız?", "Yuxuda danışırsınız?",
 "Gizli sevgilin kimdir?", "Mənim nəyi bəyənmirsən?", "Hazırda hansı rəngli alt paltarı geyinirsən?",
 "Son göndərdiyiniz mətn nə idi?", "Yanan binadan insanları xilas etsəydiniz və bu qrupdan bir nəfəri geridə qoymalı olsaydınız, bu kim olardı?",
 "Alt paltarınızı nə qədər tez-tez yuyursunuz?", "Heç qulaq kirinin dadına baxmısınız?",
 "Heç osurub başqasını günahlandırmısan?", "Heç tərinin dadını görmüsən?",
 "Bu otaqda ən pis insan kim olardı? Niyə?",
 "Yenidən doğulsaydınız, hansı əsrdə doğulmaq istərdiniz?", "Dediyiniz və ya etdiyiniz bir şeyi silmək üçün keçmişə qayıtmaq imkanınız olsaydı, bu neçənci il olardı?",
 "Sevgiliniz və ya sevgiliniz sizi heç vaxt utandırıbmı?", "Birdən görünməz olsanız nə edərdiniz?",
 "Hamamda ən çox nə vaxt qalmısan və niyə belə uzun müddət qalmısan?", "Mənə gördüyüm ən qəribə yuxudan danış.",
 "Duşa işeyirsən?", "Hələ də etdiyin ən uşaqca şey nədir?", "Hansı uşaq filminə təkrar-təkrar baxa bilərsən?",
 "Ayağınızın pis qoxusunuz varmı?", "Axmaq ləqəbləriniz varmı?", "Telefonunuzda ən çox hansı proqramda vaxt keçirirsiniz?",
 "Bir oturuşda yediyiniz ən çox yemək hansıdır?", "Tək qalanda rəqs edirsiniz?", "Qaranlıqdan qorxursan?",
 "Bütün günü evdə olsaydınız nə edərdiniz?", "Gündə neçə selfi çəkirsiniz?", "Axırıncı dəfə dişlərinizi nə vaxt fırçaladınız?",
 "Sevdiyiniz pijama nəyə bənzəyir?", "Heç yerdən bir şey yemisiniz?",
 "Bədəninizin hansı hissəsini sevirsiniz, hansı nahiyəni nifrət edirsiniz?", "Heç bitlə qarşılaşmısınızmı?",
 "Heç şalvarını kəsmisən?", "Boşqabını yalayırsan?", "Sənin haqqında heç kimin bilmədiyi nədir?",
 "Heç boşqabınızı yalamısınızmı?", "Dirsəyinizi yalaya bilirsinizmi?", "Burada hər kəsi yanan binadan xilas etməyə çalışsaydınız və kimisə geridə qoymalı olsaydınız, kimi tərk edərdiniz?",
 "Telefonda ən son nə axtardınız?", "Telefonunuzdan bir proqramı silməli olsaydınız, hansını silərdiniz?", "Bir münasibətdə ən böyük qorxunuz nədir?",
 "Otaqdakı hər bir insan haqqında bir müsbət və bir mənfi söz deyin.","Sevmədiyiniz pis vərdişləriniz varmı?",
 "Həyatınızda etdiyiniz ən çılğın şey nədir?", "Üç gün bir adada qapalı qalsanız, bu qrupdan kimi seçərdiniz?",
 "Bu otaqda ən əsəbi insan kimdir?", "Bu qrupdan biri ilə evlənməli olsaydınız, bu kim olardı?", "Ən uzun münasibətiniz nə qədər idi?",
 “Bir məşhur sizi İnstaqramda izləsəydi, o məşhurun ​​kim olmasını istərdiniz?”, “İnstaqramda 5 nəfəri silməli olsaydınız, kimi silərdiniz?”,
 "Neçə uşaq sahibi olmaq istərdiniz?", "Xəyallarınızdakı insanı təsvir edin.", "Messi yoxsa Ronaldo?", "Pes yoxsa Fifa?",
 "İlk işiniz nə olub?", "Kolleclə bağlı ən böyük qorxunuz nədir?", "Ən yaxşı dostunuzun sizinlə eyni universitetə ​​getməsini istərdinizmi?",
 "Hazırkı sevgilinizin və ya sevgilinizin sizinlə eyni universitetə ​​getməsini istərdinizmi?", "Xəyal etdiyiniz iş nədir?",
 "Heç bir dərsdə uğursuz olmusunuzmu?", "Heç aldatmısınız?", "Dərsdə yatmısınızmı?", "Dərsdə heç vaxt kimin yanında oturmaq istəməzdiniz?", "Heç dərsə gecikmisiniz?", "Müəllim qarşısında etdiyiniz ən utanc verici şey nədir?", "Heç stolun altına saqqız qoymusunuz?", "Məktəbdə nə vaxtsa dava etmisiniz?", "Sınaqda ən pis balınız nə olub?", "Sinifdə yatmısınızmı?", "Heç həbs olundunuzmu?",
 "Görünməz olsaydınız hansı sinifə girərdiniz?", "Ən pis qrup hansıdır?", "Bu qrupda sirr saxlamaqda ən çox kim çətinlik çəkir?",
 "Son danışdığınız yalan nə idi?", "İdmanla məşğul olursan?", "Ömrün boyu yalnız bir paltar geyinə bilsəydin, hansı rəngdə olardı?",
 "Sizcə Türkiyənin təhsil sistemində edilməsi lazım olan ən əhəmiyyətli dəyişiklik nədir?","Qaranlıqdan/yüksəkliklərdən qorxursunuzmu?",
 "Öz baxışlarınızı 1-dən 10-a kimi qiymətləndirin :)","İndiyə qədər etdiyiniz ən qeyri-qanuni iş nə olub?","İndi bəyənmədiyiniz bir insana evlilik təklifi almışsınızsa və bu sonuncu evlilik olubsa. sizə təklif olsa, qəbul edərdiniz?",
 "Hazırkı əhvalınıza görə hansı filmə baxırsınız (aksiya/drama/elmi-fantastik/romantik komediya/bioqrafiya/fantastika)",
 "Ən çox itirdiyiniz an hansı olub?", "Gələcəkdə uşağınız olsa, hansı adı qoymaq istərdiniz?",
 "Bir təkbuynuzlu və ya əjdahaya sahib olmaq istərdinizmi?", "Neçə qız yoldaşınız var?",
 "sevimli mahnı?", "Heç etməməli olduğun bir şeyi edərkən yaxalanmısan?", "Sevdiyiniz sənətçi kimdir?",
 "Qarşı cinsdə ilk diqqətinizi çəkən şey nədir?", "Bu il həyatınızda nəyi dəyişməyə uyğun görürsünüz?",
 "Birinin telefonunda gördüyünüz ən qəribə şey nədir?", "Super qəhrəmanlar həqiqətən mövcud olsaydı dünya necə olardı?",
 "Həyatın sizə öyrətdiyi ən mühüm dərs nədir?", "Mədəniyyətimizin ən çox sevdiyiniz hissəsi nədir?", "Ailənizin ən qəribə ənənəsi nədir?",
 "Ailənizdən başqa, həyatınıza ən çox kim təsir edir?", "Qadın/kişi olmağın ən pis və ən yaxşı tərəfi nədir?",
 "Əgər beyninizi robota qoyub sonsuza qədər belə yaşaya bilsəydiniz, bunu edərdiniz?", "Evinizdə gördüyünüz ən pis qonaq kim idi və nə baş verdi?",
 "İnsanların sizdən nə soruşmasından bezdiniz?", "Ən qəribə qorxunuz nədir?", "Ən sevdiyiniz televiziya şousu hansıdır?", "İndiyə qədər yaşadığınız ən axmaq mübahisə hansıdır?",
 "Son danışdığınız yalan nədir?", "Tanışlıq zamanı etdiyiniz ən utanc verici şey nə idi?",
 "Heç təsadüfən avtomobilinizlə (əgər varsa) nəyisə və ya kiməsə vurmusunuz?",
 "Sevdiyinizi düşündüyünüz, amma anlaşa bilmədiyiniz birisi olubmu?", "Ən qəribə ləqəbiniz nədir?",
 "Fiziki olaraq ən ağrılı təcrübəniz nə olub?"
 “İctimai nəqliyyatda etdiyiniz ən çılğın şey nədir?”, “Şüşədən cin çıxsaydı, üç arzunuz nə olardı?”, “Dünyada kimisə Türkiyənin prezidenti edə bilsəydiniz, kim edərdiniz? olmaq?",
 "Başqasına dediyiniz ən qəddar söz nədir?", "Birini öpərkən özünüzü pis hiss etmisinizmi?", "Bunun heç bir nəticəsi olmayacağını bilsəniz nə edərdiniz?",
 "Güzgü qarşısında etdiyiniz ən çılğın şey nədir?", "Başqasına dediyiniz ən mənalı şey nədir?",
 "Dostlarınla ​​etməyi sevdiyin, amma sevgilinin yanında heç vaxt etməyəcəyin bir şey nədir?", "Bu həyatda ən çox kimə qısqancsan?",
 "Sevdiyiniz pijamalarınız nəyə bənzəyir?", "Nə vaxtsa görüşdən qaçmaq üçün özünüzü xəstə kimi göstərmisinizmi?", "Görüşdüyünüz ən yaşlı insan kimdir?",
 "Gündə neçə selfi çəkirsən?", "Həftədə neçə selfi çəkirsən?",
 "Bu gün şansınız olsaydı, orta məktəbdə sevgilinizlə görüşərdiniz?", "Bədəninizin hansı hissələrini qıdıqlayırsan?",
 "Müxtəlif xurafatlarınız varmı? Əgər belədirsə, bunlar nədir?", "Hansı filmi sevdiyinizi etiraf etməkdən utanırsınız?", "Ən utanc verici özünə qulluq vərdişiniz nədir?", "Nə vaxt və sonuncusu nə olub?" üzr istədiyin zaman?","Şifahi dastanlar haqqında nə düşünürsən?",
 "Utanc verici qoxularınızın çoxu haradan gəlir?", "Heç sevgilinizə bunu söyləməyi düşünmüsünüzmü?", "Heç kimləsə sevgilinizi aldatmısınız?", "Boksçu və ya qısa tuman?", "Heç işememisinizmi?" hovuzda yoxsa dənizdə?","Heç saçınızı uzadmısınızmı? Nə qədər düşünərdiniz? ","Heç kimin bilməyəcəyinə zəmanət verilsəydi kimi öldürmək istərdiniz?","Sənə ən ucuz hədiyyə nədir? heç başqası üçün almısan?", "Vaxtınızı ən çox hansı proqramda keçirirsiniz?", "Avtobusda etdiyiniz ən qəribə iş nədir?", "Heç ictimai yerdə çılpaq olmusunuzmu?", "Gündə nə qədər dedi-qodu var?"," Tanış olmaq istədiyiniz ən gənc insanın neçə yaşı olardı? "Yaşınız haqqında heç yalan danışmısınızmı?", "Telefonunuzdan bir proqramı silməli olsaydınız, bu nə olardı?",
 "Gecə gec saatlarda etdiyiniz ən utanc verici şey nədir?", "Ən uzun müddət duş qəbul etmədiyiniz zaman nə oldu?", "Heç saxta şəxsiyyət vəsiqəsindən istifadə etmisinizmi?", "Etmək istədiyiniz məşhur kimdir?" qırmızı xalçada gəzirsən?","Gizli sevgilin kimdir? ?"
 ]
